### ISSUE TITLE
Persisting data

### ISSUE THREAD

**Issue by bptarpley** [yinlinchen/fcrepo4-docker#29]
Hello!  I'm interested in the possibility of running a dockerized version of Fedora 4, and your repo looks the most promising!  That said, I'm new to the whole Fedora repository thing, and was hoping you'd have some input on where to mount volumes in order to persist any data outside of the docker image.  Thanks in advance!

**Comment by yinlinchen** [comment]
@bptarpley  You can use volumes https://docs.docker.com/engine/admin/volumes/volumes/. Create a volume for Fedora 4 home directory, e.g. /mnt/ingest
