### ISSUE TITLE
Upgrade fcrepo4-docker to Fedora 5.0.0 once it is released. 

### ISSUE THREAD

**Issue by dbernstein** [yinlinchen/fcrepo4-docker#33]
This is a just a reminder.   Release should happen before the end of the year.

**Comment by yinlinchen** [comment]
@dbernstein Please see proposed Fedora 5 RC1 docker PR: https://github.com/fcrepo4-labs/fcrepo4-docker/pull/34

**Comment by yinlinchen** [comment]
PR: #34 merged.
