### ISSUE TITLE
Cannot Run Fedora with Camel Toolbox customization:

### ISSUE THREAD

**Issue by billyhiuwali** [yinlinchen/fcrepo4-docker#40]
Hi ,

Thank you for taking your time to read this message 

i was trying to build Fedora with Camel toolbox ,i have been stuck in it and have not idea what wrong .
https://github.com/fcrepo4-labs/fcrepo4-docker  

### step 1: edit fcrepo-camel.yaml to set the targeted Fedora version
![1](https://user-images.githubusercontent.com/31437338/89140458-4643ea00-d574-11ea-878a-c21214778c40.PNG)

### step 2: Start server
docker-compose -f fcrepo-camel.yml up -d

### step 3: after the docker-compose was finished. these message was showed

Successfully built af8a2d3b8b4b
Successfully tagged fcrepo-camel:latest
Image for service fcrepo was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating fcrepo-camel ... done

###  step 4: run docker ps -a to check the status of the container 

![2](https://user-images.githubusercontent.com/31437338/89140577-9fac1900-d574-11ea-9321-b36fde896d1b.PNG)

step 5: run docker logs to check the error message 
![3](https://user-images.githubusercontent.com/31437338/89140662-d2eea800-d574-11ea-8dc3-3844d809fcaf.PNG)

### step 6: as Step 3 suggested , try to rebuild it , so i run this command
docker-compose up --build

### step 7: now the container is up . so i access http://127.0.0.1:8080/manager/html , but i could only see  fcrepo .
![tomcat](https://user-images.githubusercontent.com/31437338/89097481-cf8edb80-d411-11ea-8dd5-c43455d2dc6a.PNG)

So i would like to know whether my Fedora with Camel toolbox is success, or i have made mistakes in these steps?

**Comment by yinlinchen** [comment]
Hi @billyhiuwali 

I just follow the commands in the [Usage section](https://github.com/fcrepo4-labs/fcrepo4-docker#usage) in the readme and check http://localhost:8181/hawtio from [Camel readme](https://github.com/fcrepo4-labs/fcrepo4-docker/tree/master/docker/services/fcrepo-camel)  and build and run successfully without any issues. 

<img width="1567" alt="Screen Shot 2020-08-03 at 4 08 39 PM" src="https://user-images.githubusercontent.com/7999195/89222790-a1410580-d5a3-11ea-8734-5f5dc13b2093.png">

Please follow the readme and you don't need to update/edit any files. 

I hope it helps.

**Comment by billyhiuwali** [comment]
@yinlinchen the comment helped me .it works now.
I really appreciate your help. Thank you.
